version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: singles_grades_getter
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SINGLES_URL=https://singles.tsukuda.ac.jp # 最後のスラッシュは不要
